# Generated by Django 2.2 on 2019-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieApp', '0005_auto_20190523_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
