# Generated by Django 2.2 on 2019-05-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieApp', '0006_auto_20190523_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
